import { Hono } from "hono";
import { zValidator } from "@hono/zod-validator";
import db from "@/server/db";
import { emails } from "@/server/db/schema";
import { desc } from "drizzle-orm";
import { emailInsertFormSchema } from "@/lib/validations/email";

const router = new Hono()
  .get("/", async (c) => {
    const data = await db.select().from(emails).orderBy(desc(emails.createdAt));
    return c.json({ data });
  })
  .post("/create", zValidator("json", emailInsertFormSchema), async (c) => {
    const data = c.req.valid("json");

    const email = await db
      .insert(emails)
      // TODO: Add title generation by message with AI
      .values({ ...data, title: "Generated by AI! (trust me bro)" });

    return c.json({ data: email });
  });

export default router;
